### ISSUE TITLE
Zooming out causes map to center on Libya

### ISSUE THREAD

**Issue by DaCor1** [stamen/fieldpapers#322] opened 2015-02-12 11:13 UTC
When I am creating papers, and I zoom out, the map centers on Libya instead of just zooming out. 

How I work around, is I hit zoom out multiple times, then click "Center Map" and it will return to original position but will only have zoomed out one level

Chrome, windows 8.1

**Comment by almccon** [comment] 2015-02-12 20:06
Sounds like a duplicate of #286. I'm not sure if there is a known workaround.

**Comment by sethfitz** [comment] 2015-06-22 18:24
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).

**Closed by sethfitz** 2015-06-22 18:24 UTC
